services:
  db:
    image: mysql:8.0
    container_name: mysql_aero
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: miguel1001
      MYSQL_DATABASE: sad_precificacao
    ports:
      - "3307:3306"
    volumes:
      - ./Scripts/init.sql:/docker-entrypoint-initdb.d/init.sql